# Generated by Django 2.1.7 on 2019-03-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
