# Generated by Django 2.1.7 on 2019-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='username',
            field=models.IntegerField(),
        ),
    ]
